branches:
  - "main"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - path: "@semantic-release/npm"
    pkgRoot: "packages/pikav-client-js"
  - path: "@semantic-release/github"
  - path: "@semantic-release/git"
    assets:
      - "package.json"
      - "package-lock.json"
      - "apps/*/package.json"
      - "packages/*/package.json"
