name: "Release"

on:
  push:
    branches:
      - main

jobs:
  node-ci-main:
    uses: timada-org/.github/.github/workflows/node-release.yml@v1.1.1
    with:
      filters: --filter client --filter solid-js
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
